### ISSUE TITLE
Table does not exists error

### ISSUE THREAD

**Issue by manikk** [kuruntham/pykalappai#1]
I had clone the project and run it. And it runs fine for the first time. Then I tried to add a scimm table in settings, with an invalid file. The UI shows error if invalid scimm tables fine. Then, when I tried to run the application error thrown.

```
======================================================
Qt: Untested Windows version 10.0 detected!
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\peewee.py", line 3090, in get
    return next(clone.execute())
  File "c:\Python34\lib\site-packages\peewee.py", line 2267, in next
    obj = self.iterate()
  File "c:\Python34\lib\site-packages\peewee.py", line 2249, in iterate
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 45, in <module>
    main = Main()
  File "app.py", line 39, in __init__
    ekWindow = EKWindow()
  File "f:\projects\pykalappai\Controllers\EKWindow.py", line 41, in __init__
    self.icon_activated(QSystemTrayIcon.Trigger)
  File "f:\projects\pykalappai\Controllers\EKWindow.py", line 242, in icon_activated
    self.change_status()
  File "f:\projects\pykalappai\Controllers\EKWindow.py", line 234, in change_status
    self.load_keyboard()
  File "f:\projects\pykalappai\Controllers\EKWindow.py", line 333, in load_keyboard
    DatabaseManager.get_keyboard_path(DatabaseManager.get_current_keyboard())
  File "f:\projects\pykalappai\database\DatabaseManager.py", line 150, in get_keyboard_path
    return LanguageSetting.get(LanguageSetting.id == keyboard_id).file_path
  File "c:\Python34\lib\site-packages\peewee.py", line 4787, in get
    return sq.get()
  File "c:\Python34\lib\site-packages\peewee.py", line 3094, in get
    % self.sql())
database.Tables.LanguageSettingDoesNotExist: Instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."language_name", "t1"."file_path" FROM "languagesetting" AS t1 WHERE ("t1"."id" = ?)
PARAMS: [1]
Exception ignored in: <bound method HookManager.__del__ of <pyHook.HookManager.HookManager object at 0x05562310>>
Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\pyHook\HookManager.py", line 279, in __del__
  File "c:\Python34\lib\site-packages\pyHook\HookManager.py", line 299, in UnhookKeyboard
AttributeError: 'HookManager' object has no attribute 'keyboard_hook'
=========================================
```

**Comment by mohanrex** [comment]
There is no scim tables assigned to the keyboard. Thats why app is throwing error and shutsdown. I'm planning to add default SCIM tables. Is that ok or else we have to show the error message to add some SCIM tables before switching on the app.

**Comment by mohanrex** [comment]
For simple workaround, please remove the ekalappai.db sqlite file from the app and try to run the app once again.

**Comment by manikk** [comment]
Defaults would be a best option.

**Comment by mohanrex** [comment]
I hope my recent changes would have fixed this error. Let me know, if the error happens again @manikk
